### ISSUE TITLE
Installation steps description - Readme/Wiki

### ISSUE THREAD

**Issue by mbettan** [benc-uk/csa-widgets#2]
Wording for Installation steps - TAG as Enchancement
# Installation steps

Open the HTML file for the widget you want in a text editor, copy and paste the content of the html file into the "Add Mashup Widget" dialog Box in CSA located in Organizations/<organisationName>/Dashboard Widgets. See below:
![add_mashup](https://cloud.githubusercontent.com/assets/14251830/10383737/0d451d1c-6e33-11e5-9d88-b3396f368977.png)

Some extra files are required for the Quota Widget:
- Create a folder named quotas in the following location: <csa_base_dir>\portal\node_modules\mpp-ui\dist\quotas place the quota text files in this folder. The zip file contains some examples inside the quotas folder.
- quotas\defaults.txt – CSA system wide quota. Must have at least this file in place
- quotas<org_name>.txt – Override quotas for specified CSA organsiation. Ignored if file not found
- quotas<username>.txt – Override quotas for specified user. Ignored if file not found
- Place the two JavaScript files jquery.flot.js and jquery.flot.pie.js found in the zip file scripts folder into <csa_base_dir>\portal\node_modules\mpp-ui\dist\scripts
  Some extra files are required for the Subscriptions by Day Widget:
- Place the four JavaScript files jquery.flot.js, jquery.flot.categories.js, jquery.flot.stack.js and jquery.flot.resize.js  found in the zip file scripts folder into <csa_base_dir>\portal\node_modules\mpp-ui\dist\scripts

Some extra files are required for the Current Services Widget:
- Place the two JavaScript files jquery.flot.js and jquery.flot.pie.js found in the zip file scripts folder into <csa_base_dir>\portal\node_modules\mpp-ui\dist\scripts
  Some extra files are required for the Generic Widget:
- Create a folder named genericXML in the location:  <csa_base_dir>\portal\node_modules\mpp-ui\dist\genericXML and place the xml file parsed by the widget in this folder. The zip file contains an example genericXML\generic_input.xml
- Create a folder named images where you can add the images to display on the widge. The zip file contains an example images\vmwareLogo.jpg.

Signed-off-by: Michaël Bettan mbe@hpe.com

**Comment by benc-uk** [comment]
I've fixed some of the wording on the wiki page and put detailed install steps
