### ISSUE TITLE
Github basic website to show widgets samples

### ISSUE THREAD

**Issue by mbettan** [benc-uk/csa-widgets#3]
Create a github basic website (settings) to show widgets samples in the website, as well as ZIP/tarball to download, without going to github project.

**Comment by benc-uk** [comment]
I've created this wiki page which shows the sample images of the widgets https://github.com/benc-uk/csa-widgets/wiki/Widget-Preview-Images

Not sure we need a zip download, as people can simply click the "Download Zip" from GitHub or access this URL https://github.com/benc-uk/csa-widgets/archive/master.zip

**Comment by mbettan** [comment]
You can enable the "autogenerate website" in the settings in your master repository. It will generate an automatic website if you ZIP and TARBALL from the last release.

**Comment by benc-uk** [comment]
Yes I was playing about with that yesterday, I realise now that is what you meant!!
I've enabled it and created a simple page - it is online here: http://benc-uk.github.io/csa-widgets/

**Comment by mbettan** [comment]
It's Perfect.
